### PR TITLE
Fixes being able to connect to the wrong slot

### LINKED ISSUE #87: Wrong seed connections
the Mod will happily connect to any AP server that matches the slot name/port without checking the seed to make sure that its correct.

not typically an issue in normal AP play as the port almost always changes, but it could mess up an Async as those always use the same port if you connect to it with a previous asynch save file.

### PR DESCRIPTION
**Pull request by dewiniaid**
Saves the AP seed and slot seed as part of ConnectionDetails, and validates it on reconnecting.

If validation fails, the user is kicked back to the main menu.  We ought to display an error message but this at least prevents accidentally sending a bunch of items to the wrong multiworld.

Closes #87

### CODE REVIEW

File: Archipelago.HollowKnight/Archipelago.cs [hunk 1]
```diff
@@ -17,6 +17,7 @@
 using ItemChanger.Tags;
 using Modding;
 using UnityEngine;
+using UnityEngine.SceneManagement;
```
Comment (Ijwu) [inline Archipelago.HollowKnight/Archipelago.cs:20]: Probably no longer necessary

File: Archipelago.HollowKnight/Archipelago.cs [hunk 2]
```diff
@@ -234,13 +235,25 @@ public void StartOrResumeGame(bool randomize)
             {
                 LogDebug("StartOrResumeGame: Beginning first time randomization.");
                 ApSettings.ItemIndex = 0;
+                ApSettings.Seed = Convert.ToInt32((long)loginResult.SlotData["seed"]);
```
Comment (Ijwu) [inline Archipelago.HollowKnight/Archipelago.cs:238]: I'm not sure there's a reason to cast to `long` then `Convert.ToInt32()`. Couldn't you cast to an `int` and be done with it?

File: Archipelago.HollowKnight/Archipelago.cs [hunk 3]
```diff
@@ -234,13 +235,25 @@ public void StartOrResumeGame(bool randomize)
...
+                LogDebug($"StartOrResumeGame: Room: {ApSettings.RoomSeed}; Seed = {ApSettings.RoomSeed}");
 
                 var randomizer = new ArchipelagoRandomizer(loginResult.SlotData);
                 randomizer.Randomize();
                 pendingGeo = SlotOptions.StartingGeo;
             }
             else
             {
+                LogDebug($"StartOrResumeGame: Local : Room: {ApSettings.RoomSeed}; Seed = {ApSettings.Seed}");
+                var seed = Convert.ToInt32((long)loginResult.SlotData["seed"]);
```
Comment (Ijwu) [inline Archipelago.HollowKnight/Archipelago.cs:250]: Same here on the casting/conversion stuff.

File: Archipelago.HollowKnight/ConnectionDetails.cs [hunk 4]
```diff
@@ -7,5 +7,8 @@ public record ConnectionDetails
         public string SlotName { get; set; }
         public string ServerPassword { get; set; }
         public int ItemIndex { get; set; }
+
+        public string RoomSeed { get; set; }
```
Comment (Ijwu) [inline Archipelago.HollowKnight/ConnectionDetails.cs:11]: This doesn't appear to be used.

File: Archipelago.HollowKnight/Archipelago.cs (hunk 1 above)
Comment (dewiniaid) [reply Archipelago.HollowKnight/Archipelago.cs:20]: Oops, that was left in when I was trying to figure out how to actually change to the menu scene.  Definitely not needed.

File: Archipelago.HollowKnight/Archipelago.cs (hunk 2 above)
Comment (dewiniaid) [reply Archipelago.HollowKnight/Archipelago.cs:238]: ... because I lifted the code from somewhere else that does that, presumably because of being used to seed a RNG.

Changed to longs throughout.

File: Archipelago.HollowKnight/ConnectionDetails.cs (hunk 4 above)
Comment (dewiniaid) [reply Archipelago.HollowKnight/ConnectionDetails.cs:11]: It's set and checked in StartOrResumeGame() as part of `ApSettings`

**Review by Ijwu — APPROVED** [review]
